#!/usr/bin/env bash
set -eu

repo_uri="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
source_branch="feature/gh-pages"
target_branch="gh-pages"
build_dir="/tmp/dist"

cd "$GITHUB_WORKSPACE"

echo "$NEXT_PUBLIC_INFURA_KEY"
exit 0

git config user.name "$GITHUB_ACTOR"
git config user.email "${GITHUB_ACTOR}@bots.github.com"
git fetch
git checkout "$source_branch"

yarn install
yarn build
yarn export -o $build_dir

git checkout "$target_branch"

mv .git "$build_dir"
cd "$build_dir"
touch .nojekyll
echo -n "chainlink-fullstack.demo.hack.bg" > CNAME

git add .
git commit -m "update GitHub Pages"

if [ $? -ne 0 ]; then
    echo "nothing to commit"
    exit 0
fi

git remote set-url origin "$repo_uri"
git push --force-with-lease origin "$target_branch"
