#!/usr/bin/env bash
set -eu

repo_uri="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
source_branch="feature/gh-pages"
target_branch="gh-pages"
build_dir="/tmp/dist"
short_hash="$(git rev-parse --short=8 HEAD)"
short_subject="$(git log -1 --pretty=format:'%s')"
current_action_url="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
br="
"

cd "$GITHUB_WORKSPACE"

git config user.name "$GITHUB_ACTOR"
git config user.email "${GITHUB_ACTOR}@bots.github.com"
git fetch
git checkout "$source_branch"

yarn install
yarn build
yarn export -o "$build_dir"

git checkout "$target_branch"

mv .git "$build_dir"
cd "$build_dir"
touch .nojekyll
echo -n "chainlink-fullstack.demo.hack.bg" > CNAME
echo "[![Deploy to GitHub Pages](https://github.com/hackbg/chainlink-fullstack/actions/workflows/gh-pages.yml/badge.svg)](https://github.com/hackbg/chainlink-fullstack/actions/workflows/gh-pages.yml)" > README.md

git add .
git commit -m "⚙️ rebuild ${short_hash} [${short_subject}]${br}${br}${current_action_url}"

if [ $? -ne 0 ]; then
    echo "nothing to commit"
    exit 0
fi

git remote set-url origin "$repo_uri"
git push --force-with-lease origin "$target_branch"
